#+title: The simplest logic ever
#+startup: showall
#+options: toc:nil
#+latex_header: \usepackage{ebproof}

* The non-implicational fragment of intuitionist propositional logic

The following is pretty much the simplest logic I can think of, apart from the
one that only has implication. (Interestingly, the one that only has implication
is the one that is normally introduced when the author wants a simple logic.)

$A$, $B$, $C$, $\dotsc$ are atomic propositions, where the symbols come from
some countable alphabet. $\top$ (‘true’, ‘top’) and $\bot$ (‘absurity’,
‘bottom’) are atomic propositions.

Atomic propositions are propositions. $P$, $Q$, $R$, $\dotsc$, and $\phi$,
$\psi$, \$dotsc$ are propositions. For any two propositions, $\phi$ and $\psi$,
the formulae $(\phi\wedge\psi)$ and $(\phi\vee\psi)$ are propositions.

A /judgement/ is a pair of propositions, written $\phi\vdash\psi$. The
interpretation is that $\psi$ ‘follows from’ $\phi$. Note that this is not what
is usually done (in logic). What is usually done is that the thing on the left
of the judgement turnstile is a multiset of premises (and sometimes the thing on
the right is also a multiset). But I am trying to understand how all this is
related to categories; and thus I am looking for a morphism. I don't feel too
bad about this adjustment to nomenclature since it appears that everyone in this
field is happy to reinvent it.

While we're on the topic, note that assumptions and premises in this version are
always judgements. In classical logic, we might find a premise, $A$, to be read
‘assuming $A$, ...’, but in intuitionist logic we (must) only write
$\gamma\vdash A$, to be read ‘assuming we have a “proof of $A$ from $\gamma$,
...”’.  


* Proofs

Judgements are construced according to proofs. A proof is a connected series of
judgements, each following from the previous according to certain rules. A rule
is written
\begin{equation}
  \begin{prooftree}
    \hypo{x}
    \hypo{y}
    \hypo{\dotsc}
    \infer3[label]{\phi\vdash\psi}
  \end{prooftree},
\end{equation}
where the $x$, $y$, $\dotsc$, above the horizontal line are the premises of the proof, and
the judgment below the line is the conclusion.

The rules of proofs are as follows.

** Axiomatic judgement

For any proposition $\phi$,
\begin{equation}
\begin{prooftree}
\infer0[id]{\phi \vdash \phi}
\end{prooftree}.
\end{equation}

The idea is that the thing above the horiztonal line are the premises of the
proof; the thing below line is the concluded judgment. The text ‘id’ is a label
for this proof form.


** Conjunctive proofs

For any propositions $P$, $\phi$, and $\psi$, and judgement $P \vdash \phi\wedge\psi$,
\begin{equation}
  \begin{prooftree}
    \hypo{P \vdash \phi\wedge\psi}
    \infer1[$\wedge_\text{E1}$]{P \vdash \phi}
  \end{prooftree}
  \qquad\text{and}\qquad
  \begin{prooftree}
    \hypo{P \vdash \phi\wedge\psi}
    \infer1[$\wedge_\text{E2}$]{P \vdash \psi}
  \end{prooftree}.
\end{equation}
These two rules are sometimes called ‘conjunction elimination,’ and the labels are read
as such.

For any propositions $P$, $\phi$, and $\psi$, and judgements $P \vdash \phi$ and
$P \vdash \psi$,
\begin{equation}
  \begin{prooftree}
    \hypo{P \vdash \phi}
    \hypo{P \vdash \psi}
    \infer2[$\wedge_\text{I}$]{P \vdash \phi\wedge\psi}
  \end{prooftree}.
 \end{equation}
This rule is known as ‘conjuction introduction.’

** Disjunctive proofs

For any propositions $P$, $\phi$, and $\psi$, and judgement 
$\phi\vee\psi \vdash P$,
\begin{equation}
  \begin{prooftree}
    \hypo{\phi \vdash Q}
    \hypo{\psi \vdash Q}
    \hypo{P \vdash \phi\vee\psi}
    \infer3[$\vee_\text{E}$]{P\vdash Q}
  \end{prooftree}.
 \end{equation}
This rule is called ‘disjunction elimination.’

For any propositions $P$, $\phi$, and $\psi$, 
\begin{equation}
  \begin{prooftree}
    \hypo{P \vdash \phi}
    \infer1[$\vee_\text{I1}$]{P \vdash \phi\vee\psi}
  \end{prooftree}
  \qquad\text{and}\qquad
  \begin{prooftree}
    \hypo{P \vdash \psi}.
    \infer1[$\vee_\text{I2}$]{P \vdash \phi\vee\psi}
  \end{prooftree}.
\end{equation}
This rule is called ‘disjunction introduction.’

** Top and bottom

For any propositions, $\phi$ and $\psi$,
\begin{equation}
  \begin{prooftree}
    \hypo{\phi \vdash \bot}
    \infer1[$\bot$]{\phi \vdash \psi},
  \end{prooftree}
  \qquad\text{and}\qquad
  \begin{prooftree}
    \hypo{\top \vdash \phi}
    \infer1[$\top$]{\psi \vdash \phi},
  \end{prooftree}
\end{equation}  
Note that these have an arbitrary consequent on the bottom. A
/theorem/ is a formula $\tau$ for which we have shown $\top\vdash\tau$,
incidentally. 

** Comments

Note that the rules for conjunction and disjunction introduce or eliminate their
respective symbols on the right-hand side of judgments. The corresponding
‘left-side rules’ follow from these, however.
From conjunction elimination of the right to conjuction introduction on the left:
\begin{equation*}
  \begin{prooftree}
    \infer0[id]{\phi\wedge\psi \vdash \phi\wedge\psi}
    \infer1[$\wedge_\text{E}$]{\phi\wedge\psi \vdash \phi}
  \end{prooftree}
  \quad\implies\quad
  \begin{prooftree}
    \infer0{\phi\wedge\psi \vdash \phi}
  \end{prooftree}
\end{equation*}

From conjunction introduction on the right to conjuction elimination on the
left:
\begin{equation*}
  \begin{prooftree}
    \hypo{
    \infer0[id]{\phi\wedge\psi \vdash \phi\wedge\psi}
    \infer1[$\wedge_\text{E}$]{\phi\wedge\psi \vdash \phi}
  \end{prooftree}
  \quad\implies\quad
  \begin{prooftree}
    \infer0{\phi \vdash P}
  \end{prooftree}
\end{equation*}

