#+title: The simplest logic ever
#+startup: showall
#+options: toc:nil

* The non-implicational fragment of intuitionist propositional logic

The following is pretty much the simplest logic I can think of, apart from the
one that only has implication. (Interestingly, the one that only has implication
is the one that is normally introduced when the author wants a simple logic.)

$A$, $B$, $C$, $\dotsc$ are atomic propositions, where the symbols come from
some countable alphabet. $\top$ (‘true’, ‘top’) and $\bot$ (‘absurity’,
‘bottom’) are atomic propositions.

Atomic propositions are propositions. $P$, $Q$, $R$, $\dotsc$, and $\phi$,
$\psi$, \$dotsc$ are propositions. For any two propositions, $\phi$ and $\psi$,
the formulae $(\phi\wedge\psi)$ and $(\phi\vee\psi)$ are propositions.

A /judgement/ is a pair of propositions, written $\phi\vdash\psi$. The
interpretation is that $\psi$ ‘follows from’ $\phi$.

The rules of judgement say which judgements exist. The rules of judgement are as
follows:

** Axiomatic judgement

For any proposition $\phi$,
\begin{equation}
\phi \vdash \phi.
\end{equation}

** Top and bottom

For any proposition, $\phi$,
\begin{equation}
\bot \vdash \phi,
\end{equation}
and
\begin{equation}
\phi \vdash \top.
\end{equation}
A /theorem/ is a formula $\tau$ for which we have shown $\top\vdash\tau$,
incidentally.

** Conjuctive and disjunctive judgements

For any two propositions, $\phi$ and $\psi$,
\begin{equation}
\phi\wedge\psi \vdash \phi\qquad\text{and}\qquad
\phi\wedge\psi \vdash \psi.
\end{equation}
(This rule is sometimes called ‘conjunction elimination.’) 

For any two propositions, $\phi$ and $\psi$,
\begin{equation}
\phi \vdash \phi\vee\psi \qquad\text{and}\qquad
\phi \vdash \phi\vee\psi.
\end{equation}
(This rule is sometimes called ‘disjunction introduction.’)

** Combinations

Some rules say how to combine judgements to get new judgements. We write the
judgements we have on top of a horizontal rule; and the judgements we obtain on
the bottom. The rules are as follows.

\begin{equation}
\end{equation}
