#+title: The simplest logic ever
#+startup: showall
#+options: toc:nil
#+latex_header: \usepackage{ebproof}

* Introduction

The subject of formal logic is frankly confusing. There are multiple kinds of
logic (classical, intuitionistic, ...) and multiple approaches to the formalism
(‘Hilbert style,’ ‘natural deduction,’ ‘sequent calculus’). References in the
subject are full of phrases like ‘Unfortunately, the computational significance
is somewhat obscured by syntactic complications that, although certainly
immaterial, have never really been overcome,’ [fn:1]which are not
reassuring. It’s asserted that intuisionistic logic is the same as a typed
lambda calculus and that both are really some kind of category. 

I don't know what much of this means. I thought I would have a go at running the
whole subject for some trivial subpart of logic. Specifically, that ‘fragment’
(as they say) which includes only propositions built from $\wedge$
(/conjunction/, meaning ‘and’) and $\vee$ (/disjunction/, meaning ‘or.’) 

* Natural deduction, intuitionistic logic

There is given a set of /propositions/, constructed as follows:

$A$, $B$, $C$, $\dotsc$ are /atomic propositions/, where the symbols come from
some countable alphabet. $\top$ (‘true’, ‘top’) and $\bot$ (‘absurity’,
‘bottom’) are atomic propositions.

Atomic propositions are propositions. $P$, $Q$, $R$, $\dotsc$, and $\phi$,
$\psi$, $\dotsc$ are propositions. For any two propositions, $\phi$ and $\psi$,
the formulae $(\phi\wedge\psi)$ and $(\phi\vee\psi)$ are propositions.

The interpretation of this propositions is different in classical and
intuitionistic logic. In classical logic, to assert the proposition $A$ is to
assert that whatever is meant by $A$ is /true/. In intuitionistic logic, to
assert $A$ is to say that one has a /proof/ of $A$. It's possibly best not to
dwell on this too much and just to go with the flow.

Give some collection of propositions it may be that some of them are true (or,
at any rate, that we have a proof of them). 

Here are the rules that are used to construct proofs. One imagines writing the
premises of the argument at the top, then drawing a horizontal line where the
rules say one may make a deduction, them writing the conclusion below the
line. Lines are typically labelled by the rule that one used to draw the
conclusion.

** The rules of conjunction

\begin{equation}
  \begin{prooftree}
    \hypo{P}
    \hypo{Q}
    \infer2[$\wedge_{\text{I}}$]{P \wedge Q}
  \end{prooftree}
\end{equation}
and
\begin{equation}
  \begin{prooftree}
    \hypo{P \wedge Q}
    \infer1[$\wedge_{\text{E1}}$]{P}
  \end{prooftree}
  \qquad\text{and}\qquad
  \begin{prooftree}
    \hypo{P \wedge Q}
    \infer1[$\wedge_{\text{E2}}$]{Q}
  \end{prooftree}.
\end{equation}

The intended interpration of the first rule, known as ‘conjunction
introduction,’ is something like, ‘from (a proof of) $P$ and (a proof of) $Q$
one may obtain (a proof of) $P∧Q$. The second pair of rules, ‘conjunction
elimination,’ say the converse: given $P∧Q$, one may obtain either $P$ or $Q$ or
both.

** The rules of disjunction

\begin{equation}
  \begin{prooftree}
    \hypo{P}
    \infer1[$\vee_{\text{I1}}$]{P \vee Q}
  \end{prooftree}
  \qquad\text{and}\qquad
  \begin{prooftree}
    \hypo{Q}
    \infer1[$\vee_{\text{I2}}$]{P \vee Q}
  \end{prooftree}
\end{equation}
and
\begin{equation}
  \begin{prooftree}
    \hypo{P \vee Q}
    \hypo{[P]}
    \ellipsis{}{R}
    \hypo{[Q]}
    \ellipsis{}{R}
    \infer3[$\vee_{\text{E}}$]{R}
  \end{prooftree}.
\end{equation}

There would be a pleasing duality here, were it not for the strange construction
that is the rule labelled $\vee_\text{E}$, disjunction elimination. First of
all, there is some new notation: the ellipsis $[P]̣\dotsb R$, say, means that
there is to be inserted some proof of $R$, starting from the premise $P$. The
square brackets around the premises are introduced when we apply the rule
$\vee_\text{E}$ and mean that these premises are no longer to be considered
premises of the whole proof: they are said to be ‘discharged.’

** The rules of truth and absurdity

\begin{equation}
  \begin{prooftree}
    \hypo{P}
    \rewrite{}
    \infer1[$\top_{\text{I}}$]{\top}
  \end{prooftree}
  \qquad\text{and}\qquad
  \begin{prooftree}
    \hypo{\bot}
    \infer1[$\bot_{\text{E}}$]{P}
  \end{prooftree}.
\end{equation}

The first is by way of an axiom: one is allowed to assume $\top$ starting from
nothing. In the second note that the conclusion is an arbitrary proposition:
‘from a false proposition one can prove any proposition.’

** Example

Let’s prove that $\wedge$ distributes over $\vee$. We shall do this by assuming
$(P\wedge Q)\vee(P\wedge R)$ as a premise and obtaining $P\wedge (Q\vee R)$ as a
conclusion. (The converse will turn out not to have a proof, however.)

The proof is too large to reproduce across the page. The first part is:
 \begin{equation}
   \begin{prooftree}
     \hypo{(P \wedge Q) \vee (P \wedge R)}
     \hypo{[P \wedge Q]}
     \infer1[$\wedge_{\text{E1}}$]{P}
     \hypo{[P \wedge R]}
     \infer1[$\wedge_{\text{E1}}$]{P}    
     \infer3[$\vee_{\text{E}}$]{P}
   \end{prooftree}.
 \end{equation}

The second part is:
 \begin{equation}
   \begin{prooftree}
     \hypo{(P \wedge Q) \vee (P \wedge R)}
     \hypo{[P \wedge Q]}
     \infer1[$\wedge_{\text{E1}}$]{Q}
     \infer1[$\vee_{\text{I1}}$]{Q \vee R}
     \hypo{[P \wedge R]}
     \infer1[$\wedge_{\text{E1}}$]{R}
     \infer1[$\vee_{\text{I2}}$]{Q \vee R}
     \infer3[$\vee_{\text{E}}$]{Q \vee R}
   \end{prooftree}.
 \end{equation}

And putting the two together, where one imagines replacing the first ellipsis
with the first part and the second ellipsis with the second part:
 \begin{equation}
   \begin{prooftree}
     \hypo{(P \wedge Q) \vee (P \wedge R)}
     \ellipsis{1}{P}
     \hypo{(P \wedge Q) \vee (P \wedge R)}
     \ellipsis{2}{Q \vee R}
     \infer2[$\wedge_{\text{I}}$]{P \wedge (Q \vee R)}
   \end{prooftree}.
 \end{equation}

What is perhaps surprising is that the converse is /not/ provable. The
conclusion of the converse, $(P\wedge Q)\vee(P\wedge R)$, has the form of a
disjunction, and the only way to conclude a disjunction, with the rules as
given, is by disjunction introduction; and that requires a proof of one of the
disjuncts. By symmetry, a proof of one of the disjuncts would be a proof of the
other, /mutatis mutandis/. But no such proof can exist. For, if proofs of both
disjunct existed, they would be a valid classical proofs; but in classical logic
it is entirely possible that one of the disjuncts is false yet the disjunct is
true.

Since we can't prove something that, under the classical interpretation, is
true, this little logic $(\wedge, \vee, \top, \bot)$ is /incomplete/ with
respect to the classical interpretation. So one interesting question is, is
there an interpretation for which it is complete? I'll return to this in a later
section.

** Comments

This whole natural deduction business is to me rather unsatisfactory. The
philosophy seems to be that to assert a proposition means that one has a proof
of it; yet the only things that look like proofs are these trees of rules. Are
they supposed to be the same thing as propositions? In which case, why aren't
they written the same? Or are there really two kinds of things that are proofs?

Furthermore, the example proof given above cannot itself be a proposition
because it has undischarged premises (namely, the premise!) and the logic we
have doesn't include implication as a possible kind of proposition. Worse yet,
there are no theorems apart from $\top$. A theorem is a proposition that is the
conclusion of a proof with no premises, and the only way to proceed from no
premises is by $\top_\text{I}$.

At this stage, your standard textbook will introduce the ‘sequent calculus.’ The
following is not, as far as I can tell, the standard sequent calculus. Except,
it is likely that I do not understand the standard sequent calculus, so maybe it
is.


* ‘Sequents’

The basic idea is to retreat from the philosophy that a proposition is the set
of its proofs, and to deal directly with things that are rather like proofs. /As
it happens/, in the full version of all of this, it /is/ possible to identify
sets of proofs with propositions; but that doesn't mean they are the same thing.

A /judgement/ is a pair of propositions, written $\phi\vdash\psi$, such that
there exists a (constructive!) proof of $\psi$ given $\phi$. The plan is to
write down some axiomatic judgements, and some ways of constructing new
judgements given existing ones: we identify a judgement with its construction
(/i.e./, its proof). Finally, for reasons to be explained later, we introduce an
equivalence on judgments, and the equivalence classes will be the real objects
of study.

Note that---as far as I can tell---this is not what is usually done (in
Gentzen's sequent calculus). What is usually done is that the thing on the left
of the judgement turnstile is a multiset of premises (and in the classical
version the thing on the right is also a multiset as well). But I am trying to
understand how all this is related to categories; and thus I am looking for a
morphism. I don't feel too bad about this adjustment to nomenclature since it
appears that everyone in this field is happy to reinvent it.

** Proofs

Judgements are constructed according to proofs. A proof is a connected series of
judgements, each following from the previous according to certain rules. The
rules of proofs are as follows.

** Axiomatic judgements

*** Identity

For any proposition $\phi$,
\begin{equation}
\begin{prooftree}
\infer0[id]{\phi \vdash \phi}
\end{prooftree}.
\end{equation}

*** Conjunction

For any propositions $\phi$, and $\psi$,
\begin{equation}
  \begin{prooftree}
    \infer0[$\pi_1$]{\phi \wedge \psi \vdash \phi}
  \end{prooftree}
  \qquad\text{and}\qquad
  \begin{prooftree}
    \infer0[$\pi_2$]{\phi \wedge \psi \vdash \psi}
  \end{prooftree}.
\end{equation}

*** Disjunction

For propositions $\phi$, and $\psi$,
\begin{equation}
  \begin{prooftree}
    \infer0[$\iota_1$]{\phi \vdash \phi \vee \psi}
  \end{prooftree}
  \qquad\text{and}\qquad
  \begin{prooftree}
    \infer0[$\iota_2$]{\psi \vdash \phi \vee \psi}
  \end{prooftree}.
 \end{equation}

*** Truth and falsity

\begin{equation}
  \begin{prooftree}
    \infer0[Unit]{\phi \vdash \top}
  \end{prooftree}
  \qquad\text{and}\qquad
  \begin{prooftree}
    \infer0[]{\bot \vdash \psi}
  \end{prooftree}.
 \end{equation}

** Rules of combination

As well as the axioms, we may also produce new judgements from existing
ones. The rules are as follows.

*** Conjunction

For any propositions $P$, $\phi$, and $\psi$, and judgements $P \vdash \phi$ and
$P \vdash \psi$,
\begin{equation}
  \begin{prooftree}
    \hypo{P \vdash \phi}
    \hypo{P \vdash \psi}
    \infer2[$\times$]{P \vdash \phi\wedge\psi}
  \end{prooftree}.
 \end{equation}

*** Disjunction

For any propositions $P$, $\phi$, and $\psi$, and judgements $\phi \vdash P$ and
$\psi \vdash P$, 
\begin{equation}
  \begin{prooftree}
    \hypo{\phi \vdash P}
    \hypo{\psi \vdash P}
    \infer2[$+$]{\phi \vee \psi \vdash P}
  \end{prooftree}.
 \end{equation}

** Rule of composition

For propositions $P$, $Q$, and $R$, and judgements $P\vdash Q$ and $Q\dash R$,
\begin{equation}
  \begin{prooftree}
    \hypo{P \vdash Q} \hypo{Q \vdash R}
    \infer2[$\circ$]{P \vdash R}
  \end{prooftree}.
\end{equation}

** Example

Let's try to prove 

** Comments 

The rule of composition, in the traditional presentation, is known as the ‘cut
rule.’ It is disliked because, unlike the other rules, it has a proposition in
the premise, $Q$, which does not occur in the conclusion. If one is trying to
write an automated theorem prover this is something of a problem. An automated
theorem prover will search backwards from conclusions and if the cut is allowed
then the search space for premises is unbounded. 

There is a thereom, called ‘Hauptsatz,’ or ‘cut elimination’ to the effect that
any construction involving cut can be replaced by one not involving cut.
 

*** OLD

** Comments

 Note that the rules for conjunction and disjunction introduce or eliminate their
 respective symbols on the right-hand side of judgments. The corresponding
 ‘left-side rules’ follow from these, however.

 From conjunction elimination of the right to conjuction introduction on the left:
 \begin{equation*}
   \begin{prooftree}
     \infer0[id]{\phi\wedge\psi &\vdash \phi\wedge\psi}
     \infer1[$\wedge_\text{E1}$]{\phi\wedge\psi &\vdash \phi}
   \end{prooftree}
   \quad\implies\quad
   \begin{prooftree}
     \infer0[$\wedge_{\text{II1}}$]{\phi\wedge\psi \vdash \phi}
   \end{prooftree}
 \end{equation*}
 (and /mutatis mutandis/ for $\wedge_{\text{E2}}$).

 From conjunction introduction on the right to conjuction elimination on the
 left:
 \begin{equation*}
   \begin{prooftree}
     \infer0[id]{\phi\wedge\psi \vdash \phi\wedge\psi}
     \infer1[$\wedge_\text{E}$]{\phi\wedge\psi \vdash \phi}
   \end{prooftree}
   \quad\implies\quad
   \begin{prooftree}
     \hypo{P \vdash \phi}
     \hypo{P \vdash \psi}
     \hypo{\phi\wedge\psi \vdash Q}
     \infer3[$\wedge_\text{EE}$]{P \vdash Q}
   \end{prooftree}
 \end{equation*}

* Footnotes

[fn:1] Jean-Yves Girard, /Proofs and Types/ (available from
http://paultaylor.eu/stable/prot.pdf).  
